//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBridge {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if NetCore
                    var assembly = typeof(Resources).GetTypeInfo().Assembly;
#else
                    var assembly = typeof(Resources).Assembly;
#endif
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceBridge.Resources", assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation error occurred while trying to get all instances of type {0}..
        /// </summary>
        internal static string ActivateAllExceptionMessage {
            get {
                return ResourceManager.GetString("ActivateAllExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation error occurred while trying to get instance of type {0}, key &quot;{1}&quot;..
        /// </summary>
        internal static string ActivationExceptionMessage {
            get {
                return ResourceManager.GetString("ActivationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a registration for the requested service &apos;{0}&apos; with the default name, and cannot be registered again..
        /// </summary>
        internal static string DuplicateDefaultRegistrationMessage {
            get {
                return ResourceManager.GetString("DuplicateDefaultRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a registration for the requested service &apos;{0}&apos; with the specified name &apos;{1}&apos;, and cannot be registered again..
        /// </summary>
        internal static string DuplicateNamedRegistrationMessage {
            get {
                return ResourceManager.GetString("DuplicateNamedRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injection error occurred while trying to inject an existing instance of type {0}..
        /// </summary>
        internal static string InjectionExceptionMessage {
            get {
                return ResourceManager.GetString("InjectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider for the service container must be set..
        /// </summary>
        internal static string ProviderNotSetMessage {
            get {
                return ResourceManager.GetString("ProviderNotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error occurred while trying to register type mapping from {0} to {1}, key &quot;{2}&quot;..
        /// </summary>
        internal static string RegistrationExceptionMessage {
            get {
                return ResourceManager.GetString("RegistrationExceptionMessage", resourceCulture);
            }
        }
    }
}
